name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install CMake
      run: apt install cmake
    - name: Build
      run: |
        cd build
        cmake ..
        make
